# SPDX-License-Identifier: MIT
set(CPACK_PACKAGE_NAME treehound)
set(CPACK_PACKAGE_VENDOR "Treehound contributors")
set(CPACK_PACKAGE_CONTACT "Treehound contributors <treehound@users.noreply.github.com>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Indexed filename search and disk-usage explorer")
set(CPACK_PACKAGE_DESCRIPTION "Native GTK4 disk usage explorer and indexed filename search. Includes an unprivileged GTK-free background daemon with SQLite FTS5 and inotify updates.")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_HOMEPAGE_URL ${PROJECT_HOMEPAGE_URL})
set(CPACK_RESOURCE_FILE_LICENSE ${PROJECT_SOURCE_DIR}/LICENSE)
set(CPACK_PACKAGING_INSTALL_PREFIX /usr)
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Treehound contributors")
set(CPACK_DEBIAN_PACKAGE_SECTION utils)
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE amd64)
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6, libgtk-4-1 (>= 4.6), libglib2.0-0, libsqlite3-0 (>= 3.34)")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_FILE_NAME "treehound_${PROJECT_VERSION}_amd64.deb")
set(CPACK_RPM_PACKAGE_LICENSE MIT)
set(CPACK_RPM_PACKAGE_GROUP "Applications/System")
set(CPACK_RPM_PACKAGE_ARCHITECTURE x86_64)
set(CPACK_RPM_PACKAGE_REQUIRES "gtk4 >= 4.6, glib2, sqlite-libs >= 3.34")
set(CPACK_RPM_FILE_NAME "treehound-${PROJECT_VERSION}-1.x86_64.rpm")
set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION /usr/lib/systemd /usr/lib/systemd/user /usr/share/icons /usr/share/icons/hicolor /usr/share/icons/hicolor/scalable /usr/share/icons/hicolor/scalable/apps /usr/share/applications)
include(CPack)
